#!/bin/bash
set +h
set -e

cd $PKGDIR
./configure --prefix=/tools --without-bash-malloc
make
# make -k tests >> $TEST_LOG 2>&1 || true
make install
ln -sv bash /tools/bin/sh
echo -e "\n\nTotalseconds: $SECONDS\n"
exit
