#!/bin/bash
set +h
set -e

cd $PKGDIR
./configure --prefix=/tools --enable-install-program=hostname
make
# make -k RUN_EXPENSIVE_TESTS=yes check >> $TEST_LOG 2>&1 || true
make install
echo -e "\n\nTotalseconds: $SECONDS\n"
exit
