#!/bin/bash
set +h
set -e

cd $PKGDIR
./configure --prefix=/tools                \
            --without-python               \
            --disable-makeinstall-chown    \
            --without-systemdsystemunitdir \
            PKG_CONFIG=""
make
make install
echo -e "\n\nTotalseconds: $SECONDS\n"
exit
