#!/bin/bash
set +h
set -e

cd $PKGDIR
make mrproper
make INSTALL_HDR_PATH=dest headers_install
find dest/include \( -name .install -o -name ..install.cmd \) -delete

cp -rv dest/include/* /usr/include
echo -e "\n\nTotalseconds: $SECONDS\n"
exit
