#!/bin/bash
set +h
set -e

cd $PKGDIR
./configure --prefix=/usr    \
            --disable-static \
            --docdir=/usr/share/doc/mpc-1.0.3
make
make html
# make -k check >> $TEST_LOG 2>&1 || true
make install
make install-html
echo -e "\n\nTotalseconds: $SECONDS\n"
exit
