#!/bin/bash
set +h
set -e

cd $PKGDIR
sed -i -e 's|/@pkg_name@|&-@pkg_version@|' include/builddefs.in
sed -i -e "/SUBDIRS/s|man[25]||g" man/Makefile
./configure --prefix=/usr \
            --bindir=/bin \
            --disable-static
make
# make -k -j1 tests root-tests >> $TEST_LOG 2>&1 || true
make install install-dev install-lib
chmod -v 755 /usr/lib/libattr.so
mv -v /usr/lib/libattr.so.* /lib
ln -sfv ../../lib/$(readlink /usr/lib/libattr.so) /usr/lib/libattr.so
echo -e "\n\nTotalseconds: $SECONDS\n"
exit
