#!/bin/bash
set +h
set -e

cd $PKGDIR
patch -Np1 -i ../bc-1.06.95-memory_leak-1.patch
./configure --prefix=/usr           \
            --with-readline         \
            --mandir=/usr/share/man \
            --infodir=/usr/share/info
make
# echo "quit" | ./bc/bc -l Test/checklib.b >> $TEST_LOG 2>&1
make install
echo -e "\n\nTotalseconds: $SECONDS\n"
exit
