#!/bin/bash
set +h
set -e

cd $PKGDIR
./configure --prefix=/usr --docdir=/usr/share/doc/gperf-3.0.4
make
# make -k -j1 check >> $TEST_LOG 2>&1 || true
make install
echo -e "\n\nTotalseconds: $SECONDS\n"
exit
