#!/bin/bash
set +h
set -e

cd $PKGDIR
./configure --prefix=/usr --disable-static
make
# make -k check >> $TEST_LOG 2>&1 || true
make install
install -v -dm755 /usr/share/doc/expat-2.2.0
install -v -m644 doc/*.{html,png,css} /usr/share/doc/expat-2.2.0
echo -e "\n\nTotalseconds: $SECONDS\n"
exit
