#!/bin/bash
set +h
set -e

cd $PKGDIR
./configure --prefix=/usr        \
            --localstatedir=/var \
            --disable-logger     \
            --disable-whois      \
            --disable-rcp        \
            --disable-rexec      \
            --disable-rlogin     \
            --disable-rsh        \
            --disable-servers
make
# make -k check >> $TEST_LOG 2>&1 || true
make install
mv -v /usr/bin/{hostname,ping,ping6,traceroute} /bin
mv -v /usr/bin/ifconfig /sbin
echo -e "\n\nTotalseconds: $SECONDS\n"
exit
