#!/bin/bash
set +h
set -e

cd $PKGDIR
echo "127.0.0.1 localhost $(hostname)" > /etc/hosts
export BUILD_ZLIB=False
export BUILD_BZIP2=0
sh Configure -des -Dprefix=/usr                 \
                  -Dvendorprefix=/usr           \
                  -Dman1dir=/usr/share/man/man1 \
                  -Dman3dir=/usr/share/man/man3 \
                  -Dpager="/usr/bin/less -isR"  \
                  -Duseshrplib
make
# make -k test >> $TEST_LOG 2>&1 || true
make install
unset BUILD_ZLIB BUILD_BZIP2
echo -e "\n\nTotalseconds: $SECONDS\n"
exit
