#!/bin/bash
set +h
set -e

cd $PKGDIR
sed -i 's:\\\${:\\\$\\{:' intltool-update.in
./configure --prefix=/usr
make
# make -k check >> $TEST_LOG 2>&1 || true
make install
install -v -Dm644 doc/I18N-HOWTO /usr/share/doc/intltool-0.51.0/I18N-HOWTO
echo -e "\n\nTotalseconds: $SECONDS\n"
exit
