#!/bin/bash
set +h
set -e

cd $PKGDIR
sed -i 's:/\\\${:/\\\$\\{:' bin/automake.in
./configure --prefix=/usr --docdir=/usr/share/doc/automake-1.15
make
# sed -i "s:./configure:LEXLIB=/usr/lib/libfl.a &:" t/lex-{clean,depend}-cxx.sh >> $TEST_LOG 2>&1
# make -k -j4 check >> $TEST_LOG 2>&1 || true
make install
echo -e "\n\nTotalseconds: $SECONDS\n"
exit
