#!/bin/bash
set +h
set -e

cd $PKGDIR
./configure --prefix=/usr    \
            --disable-static \
            --docdir=/usr/share/doc/xz-5.2.3
make
# make -k check >> $TEST_LOG 2>&1 || true
make install
mv -v   /usr/bin/{lzma,unlzma,lzcat,xz,unxz,xzcat} /bin
mv -v /usr/lib/liblzma.so.* /lib
ln -svf ../../lib/$(readlink /usr/lib/liblzma.so) /usr/lib/liblzma.so
echo -e "\n\nTotalseconds: $SECONDS\n"
exit
