#!/bin/bash
set +h
set -e

cd $PKGDIR
sed -i '/^TESTS =/d' gettext-runtime/tests/Makefile.in &&
sed -i 's/test-lock..EXEEXT.//' gettext-tools/gnulib-tests/Makefile.in
./configure --prefix=/usr    \
            --disable-static \
            --docdir=/usr/share/doc/gettext-0.19.8.1
make
# make -k check >> $TEST_LOG 2>&1 || true
make install
chmod -v 0755 /usr/lib/preloadable_libintl.so
echo -e "\n\nTotalseconds: $SECONDS\n"
exit
