#!/bin/bash
set +h
set -e

cd $PKGDIR
patch -Np1 -i ../coreutils-8.26-i18n-1.patch
sed -i '/test.lock/s/^/#/' gnulib-tests/gnulib.mk
FORCE_UNSAFE_CONFIGURE=1 ./configure \
            --prefix=/usr            \
            --enable-no-install-program=kill,uptime
FORCE_UNSAFE_CONFIGURE=1 make
# make -k NON_ROOT_USERNAME=nobody check-root >> $TEST_LOG 2>&1 || true
# echo "dummy:x:1000:nobody" >> /etc/group
# chown -Rv nobody .  >> $TEST_LOG 2>&1
# su nobody -s /bin/bash \
#           -c "PATH=$PATH make -k RUN_EXPENSIVE_TESTS=yes check" >> $TEST_LOG 2>&1 || true
# sed -i '/dummy/d' /etc/group >> $TEST_LOG 2>&1
make install
mv -v /usr/bin/{cat,chgrp,chmod,chown,cp,date,dd,df,echo} /bin
mv -v /usr/bin/{false,ln,ls,mkdir,mknod,mv,pwd,rm} /bin
mv -v /usr/bin/{rmdir,stty,sync,true,uname} /bin
mv -v /usr/bin/chroot /usr/sbin
mv -v /usr/share/man/man1/chroot.1 /usr/share/man/man8/chroot.8
sed -i s/\"1\"/\"8\"/1 /usr/share/man/man8/chroot.8
mv -v /usr/bin/{head,sleep,nice,test,[} /bin
echo -e "\n\nTotalseconds: $SECONDS\n"
exit
