#!/bin/bash
set +h
set -e

cd $PKGDIR
./configure --prefix=/usr
make
# make -k check >> $TEST_LOG 2>&1 || true
make install
mkdir -v /usr/share/doc/gawk-4.1.4
cp    -v doc/{awkforai.txt,*.{eps,pdf,jpg}} /usr/share/doc/gawk-4.1.4
echo -e "\n\nTotalseconds: $SECONDS\n"
exit
