#!/bin/bash
set +h
set -e

cd $PKGDIR
sed -i 's/test-lock..EXEEXT.//' tests/Makefile.in
./configure --prefix=/usr --localstatedir=/var/lib/locate
make
# make -k check >> $TEST_LOG 2>&1 || true
make install
mv -v /usr/bin/find /bin
sed -i 's|find:=${BINDIR}|find:=/bin|' /usr/bin/updatedb
echo -e "\n\nTotalseconds: $SECONDS\n"
exit
