#!/bin/bash
set +h
set -e

cd $PKGDIR
./configure --prefix=/usr          \
            --sbindir=/sbin        \
            --sysconfdir=/etc      \
            --disable-efiemu       \
            --disable-werror
make
make install
echo -e "\n\nTotalseconds: $SECONDS\n"
exit
