#!/bin/bash
set +h
set -e

cd $PKGDIR
PKG_CONFIG_PATH=/tools/lib/pkgconfig ./configure --prefix=/usr
make
# make -k check >> $TEST_LOG 2>&1 || true
make install
echo -e "\n\nTotalseconds: $SECONDS\n"
exit
