#!/bin/bash
set +h
set -e

cd $PKGDIR
mkdir -pv /var/lib/hwclock
./configure ADJTIME_PATH=/var/lib/hwclock/adjtime   \
            --docdir=/usr/share/doc/util-linux-2.29.1 \
            --disable-chfn-chsh  \
            --disable-login      \
            --disable-nologin    \
            --disable-su         \
            --disable-setpriv    \
            --disable-runuser    \
            --disable-pylibmount \
            --disable-static     \
            --without-python     \
            --without-systemd    \
            --without-systemdsystemunitdir
make
# chown -Rv nobody . >> $TEST_LOG 2>&1 || true
# su nobody -s /bin/bash -c "PATH=$PATH make -k check" >> $TEST_LOG 2>&1 || true
make install
echo -e "\n\nTotalseconds: $SECONDS\n"
exit
