#!/bin/bash
set +h
set -e

cd $PKGDIR
./configure --prefix=/usr --disable-static
make
# make -k check >> $TEST_LOG 2>&1 || true
make install
make TEXMF=/usr/share/texmf install-tex
echo -e "\n\nTotalseconds: $SECONDS\n"
exit
