#!/tools/bin/bash
set +h

/tools/bin/find /usr/lib -type f -name \*.a \
#    -exec /tools/bin/strip --strip-debug {} ';' || true

/tools/bin/find /lib /usr/lib -type f -name \*.so* \
#    -exec /tools/bin/strip --strip-unneeded {} ';' || true

/tools/bin/find /{bin,sbin} /usr/{bin,sbin,libexec} -type f \
#     -exec /tools/bin/strip --strip-all {} ';' || true
echo -e "\n\nTotalseconds: $SECONDS\n"
exit
