#!/bin/bash
set +h
set -e

cd /etc/sysconfig/
cat > ifconfig.eth0 << "EOF"
ONBOOT=yes
IFACE=eth0
SERVICE=ipv4-static
IP=10.0.2.9
GATEWAY=10.0.2.2
PREFIX=24
BROADCAST=10.0.2.255
EOF
cat > /etc/resolv.conf << "EOF"
# Begin /etc/resolv.conf

domain local
nameserver 10.0.2.3
nameserver 8.8.8.8

# End /etc/resolv.conf
EOF
echo "abel-lfs" > /etc/hostname
cat > /etc/hosts << "EOF"
# Begin /etc/hosts (network card version)

127.0.0.1 localhost
10.0.2.9 abel-lfs 

# End /etc/hosts (network card version)
EOF
echo -e "\n\nTotalseconds: $SECONDS\n"
exit
